package cs5279_recipe_parser;

import java.io.IOException;
import java.util.List;
import RecipeLineProcessor;

public class Main {

    public static void main(String[] args) {
        // Example paragraph with multiple lines
        String paragraph = "Add onion, and sea salt cook for 1 minute.\n"
        				 + "Cook salt for \n"
                         + "Here is the second line.\n"
                         + "Add the chicken cook for a few hours (no more than 2).\n"
                         + "Add chicken and fish sauce, and fry until cooked, around 2 minutes.\n"
                         + "Prepare noodles per packet directions.\n"
                         + "Mix Sauce in a small bowl.\n"
                         + "Heat oil in wok or large heavy based skillet over high heat.\n"
                         + "Add garlic and chilli and cook for 10 seconds. Don't inhale - the chilli will make you cough!\n"
                         + "Add onion, cook for 1 minute.\n"
                         + "Add chicken and fish sauce, and fry until cooked, around 2 minutes.\n"
                         + "Add green onion, noodles and sauce and cook for 1 minute until the sauce reduces and coats the noodles.\n"
                         + "Remove from heat and immediately add basil, toss until just wilted, then serve immediately.\n"
                         + "add onions and cook for 1 minute. add garlic, sautee for 1 minute.\n"
        				 + "add onions and cook for 1 minute. add garlic, cook for another minute.\n"
        				 + "Preheat the oven to 350 degrees F (175 degrees C). Grease a 10-inch springform pan.\n"
        				 + "Combine sugar and butter in a large bowl and beat with an electric mixer until light and fluffy. Add eggs, 1 at a time, and beat well after each addition. Combine flour, baking powder, and salt in a separate bowl and sift on top of the butter mixture; mix to combine. Transfer batter into the prepared springform pan and smooth out.\n"
        				 + "Set plums inside batter, cut-side up, and sprinkle evenly with cinnamon-sugar.\n"
        				 + "Bake in the preheated oven on the lowest rack until a toothpick inserted into the center comes out clean, 40 to 50 minutes. Serve warm or cool to room temperature.\n"
        				 + "cook the chilies for an hour. cook them for a minute.\n"
        				 + "Mix all ingredients in a bowl or in the jar you’ll be storing them in. Pour or spoon the mixture\n"
        				 + "into the storage container.\n"
        				 + "Refrigerate for at least 4 hours, but up to 8 hours (usually overnight) for best results.\n"
        				 + "Overnight oats can be eaten cold or heated in the microwave.\n"
        				 + "Blend dry rolled oats in a blender, pulsing until oats are powdery.\n"
        				 + "In a mixing bowl combine powdery oats and remaining ingredients.\n"
        				 + "To use, combine ½ cup instant oatmeal and 2/3 cup water in a microwaveable bowl and\n"
        				 + "microwave for 2 minutes. Add toppings if desired.\n"
        				 + "If desired, put mix into individual baggies, ½ cup in each. Makes 6 packets.\n"
        				 + "Preheat oven to 400 °F.\n"
        				 + "Mix dry ingredients together well.\n"
        				 + "In a separate bowl, mix milk, oil, and egg. Make a well in the center of the dry ingredients.\n"
        				 + "Pour in the wet ingredients and stir until moistened, leaving the mixture slightly lumpy.\n"
        				 + "Fill sprayed muffin pans about 2/3 full. Bake 20-25 minutes. Makes 10-12.\n"
        				 + "In a small pot, bring 2 cups of water to a boil. While you are waiting for the water to boil,\n"
        				 + "wash and slice the veggies (spinach, mushrooms, green onions). Add the dry noodles to the\n"
        				 + "boiling water and cook for about 5 minutes. Add the seasoning packet (or half a packet if you\n"
        				 + "prefer less sodium) and stir until dissolved.\n"
        				 + "Turn the heat down to medium and stir in all of the fresh veggies. Allow them to sit in the hot\n"
        				 + "(not boiling) broth for 1-2 minutes or until slightly softened. Voila! You can go ahead and enjoy\n"
        				 + "your Ramen, or follow the next step if you’d like some protein.\n"
        				 + "Make a well in the center of the pot and crack the egg into it. Allow the egg to poach in the\n"
        				 + "broth until the whites are solid but the yolk is still runny. Alternatively, you can break the yolk\n"
        				 + "and stir the pot just slightly to yield egg ribbons like in egg drop soup. The water should not be\n"
        				 + "boiling at this point or else your egg will dissolve into such small pieces that it will give you a\n"
        				 + "cloudy broth.\n"
        				 + "Add olive oil and ground beef to a large, deep skillet. Brown the ground beef over medium\n"
        				 + "heat until cooked through. If you are not using meat, disregard this step and move on to\n"
        				 + "sautéing the onion and garlic.\n"
        				 + "While the beef is browning, finely dice onion and mince the garlic. Once the beef has\n"
        				 + "cooked through, add the onion and garlic to the skillet and continue to sauté until the onion is\n"
        				 + "soft and transparent.\n"
        				 + "While the onion and garlic are sautéing, shred the zucchini and carrots using a large-holed\n"
        				 + "cheese grater. You should have about 1 to 1.5 cups of each vegetable.\n"
        				 + "Add the shredded zucchini and carrots to the skillet along with the basil, oregano, some\n"
        				 + "freshly cracked pepper, salt, and a pinch of red pepper (optional). Continue to sauté until the\n"
        				 + "vegetables are tender.\n"
        				 + "Add the pasta sauce and heat through. Cook the spaghetti according to the package\n"
        				 + "directions then drain in a colander. Return the drained spaghetti to the pot with the heat\n"
        				 + "turned off. Add one cup of the prepared sauce to the pasta and stir to coat. Divide the pasta\n"
        				 + "into serving bowls and top with additional sauce.\n"
        				 + "Cook pasta al dente according to package directions in boiling water.\n"
        				 + "Meanwhile, heat olive oil or melt butter in a large sauté pan over medium-high heat. Add\n"
        				 + "garlic and sauté for about one minute, stirring occasionally, until fragrant. Sprinkle with flour,\n"
        				 + "and stir to combine. Sauté for an additional minute to cook the flour, stirring occasionally.\n"
        				 + "Slowly add the chicken broth, whisking to combine until smooth. Whisk in milk, and bring the\n"
        				 + "mixture to a simmer. Let the sauce cook for an additional minute until thickened, then stir in\n"
        				 + "Parmesan cheese, salt and pepper until the cheese is melted.\n"
        				 + "Drain pasta, then immediately add it to the sauce. Toss to combine. Serve topped with\n"
        				 + "chopped fresh parsley and extra parmesan if desired.\n"
        				 + "Mix together the flour, baking powder, sugar and salt in\n"
        				 + "a medium bowl. Add the spice, if desired.\n"
        				 + "In a separate bowl, beat the egg until well blended. Add\n"
        				 + "the milk and oil. Add the vanilla, if desired.\n"
        				 + "Add the dry ingredients to the liquids and stir just until\n"
        				 + "the lumps disappear.\n"
        				 + "Lightly grease and preheat a large skillet over mediumhigh heat. The skillet is hot enough when a few drops of\n"
        				 + "water sprinkled on it skitter and bounce around.\n"
        				 + "Pour ¼ cup of batter per pancake onto the hot skillet.\n"
        				 + "Cook until bubbles come to the surface of the pancake\n"
        				 + "and the edges start to look dry. Turn over. Cook until\n"
        				 + "cooked through and the bottom is golden brown.\n"
        				 + "Wash rice to drain away excess starch and then soak and set aside\n"
        				 + "Boil the rice in salted water while your masala is cooking until it is just cooked, but not tender enough to eat as is.\n"
        				 + "Heat ½ cup oil in saute mode (medium heat) and add your whole spices\n"
        				 + "When they sputter and smell toasty add your onion and green chilies and cook till the edges of the onion are golden\n"
        				 + "Now add your ginger and garlic paste, saute for a minute\n"
        				 + "Add the spices, give it a quick mix\n"
        				 + "Stir in the beef, sauteeing until the beef cubes are evenly browned.\n"
        				 + "Stir in your tomatoes, dried plums (if using), and 2 cups hot water.\n"
        				 + "Pressure cook (manual) for 14 minutes\n"
        				 + "Quick release then add the potatoes and cook for another 3 minutes (4 if your potatoes usually take a long time to cook)\n"
        				 + "Quick release and then saute to dry up the excess liquid - I like to remove my potatoes here and add them back in later to avoid breaking them. The masala should be so dry that it starts to stick to the bottom and the oil rises to the top.\n"
        				 + "Taste and adjust seasoning - you want a little salty and a little spicy - if you have not used dried plums add lemon juice at this point.\n"
        				 + "Layer half the rice in the pot you used to cook it, then the meat masala, then scatter cilantro, mint and chilies over top and follow it by the remaining half of the rice.\n"
        				 + "Mix a little food color with yogurt and drizzle over top.\n"
        				 + "Cover the pot and cook on the lowest heat for 25 minutes.\n"
        				 + "Heat a small to medium skillet over medium-low heat. Add the coriander seeds, cumin seeds, and carom seeds (if using). Toast, stirring and shaking the skillet often, for 3-4 minutes. The seeds will deepen in color and become highly aromatic. Remove from heat and transfer to a spice grinder, food processor, or mortar and pestle. Add pomegranate seeds to the spice grinder. Pulse to roughly grind 4-5 times (you don’t want a fine powder, just roughly crushed up seeds).\n"
        				 + "Skillet of coriander seeds, cumin seeds and carom seeds beside a picture of these whole spices grinded in a spice grinder.\n"
        				 + "In the same skillet over medium heat, add the corn flour or chickpea flour. Toast until it deepens in color and smells toasty (~4-5 minutes). Turn off the heat and allow to cool.\n"
        				 + "Toasted gram flour (besan) in a pan with a spatula.\n"
        				 + "In a medium bowl, add the ground beef along with the remaining ingredients (ground coriander mixture, toasted corn flour, red onion, green onion, green chili pepper, cilantro, garlic, ginger, red chili flakes, red chili powder, black pepper, salt, egg, and tomatoes (if using)).\n"
        				 + "Ingredients for Chapli Kabab combined in a bowl ready to be mixed.\n"
        				 + "Using gloved hands (try not to use bare hands or the green chili may sting), knead for 3-4 minutes, until you begin to see a lacy, stringy texture (resha) of the meat. (Alternatively, you can use the paddle attachment of a stand mixer and knead on medium speed for 2-3 minutes.) The mixture should be homogenous instead of crumbly. Cover and set aside or refrigerate up to 24 hours.\n"
        				 + "Chapli Kabab mixture ready to be formed into patties.\n"
        				 + "Heat a cast iron skillet over high heat. Add enough oil to generously cover the bottom of the skillet.\n"
        				 + "To test a piece for taste, place a piece of the beef mixture on the pan to cook, turning over as needed. Taste and adjust salt and seasoning if desired.\n"
        				 + "Using oiled hands, take around 1/4 cup heaped (~90g) of the meat and form into a hearty round shape.\n"
        				 + "Chapli Kabab Patties on parchment paper ready to be fried.\n"
        				 + "Place the round ball on the hot cast iron and use the flat part of a sturdy spatula to press it down until it is 4.5 inches in diameter and no more than 1/3-inch/¾-cm thick.\n"
        				 + "Use a spoon or small spatula to flatten and spread (uneven sides add character!). Fry for 1 ½ to 2 minutes on each side, using your spatula or a spoon to push oil on top of the kabab. Do not overcook. You want it crispy and charred on the outside and just cooked on the inside. (Internal temp 160°F/71°C)\n"
        				 + "Add 1 tbsp of corn flour or gram flour. Fry remaining kababs, replacing the oil if it starts to darken.\n"
        				 // step 113.
        				 + "Cook for half a minute\n"
        				 + "Cook for three-quarters a minute\n"
        				 + "Cook for a quarter hour\n"
        				// fixed fractions should not have to deal with mixed numbers, no one puts those in recipes.
        				 + "cook for 1/2 minute\n"
        				 + "cook for 1/2 a minute\n"
        				 + "cook for 1/4 minute\n"
        				 + "cook for 3/4 minute\n"
        				 // now lets check punctuation errors that i should have accounted for.
        				 // step 120
        				 + "around 1 minute.\n"
        				 + "around (3) minutes.\n"
        				 + "around (333) minutes.\n"
        				 + "around ((3333)) minutes.\n"
        				 + "around (((4))) minutes.\n"
        				 // this should not tell 5 since its too deep and this works.
        				 + "around ((((5)))) minutes.\n"
        				 // step 126
        				 + "cook for six minutes.\n"
        				 + "cook for fifteen hours.\n"
        				 + "around 7 8 9 hours.\n"
        				 + "add garlic second and then add chopped cook for 3-4 hours.\n"
        				 // these 3 fractions need to be fixed last one is exception bec trim
        				 // is going too far it should not clean if nothing there.
        				 + "cook for one-half an hour.\n"
        				 + "cook for one-quarter an hour.\n"
        				 + "cook for three-quarters of a minute.\n"
        				 + "around 6 ( minutes.\n"
        				 + "To a pan over medium heat, add the oil, ginger, garlic, and red curry paste. Saute for 2 to 3 minutes.\n"
        				 + "Add the fish sauce, coconut milk, lime juice, brown sugar, red pepper flakes, and salt. Mix together and bring to a boil.\n"
        				 + "Add the chicken and cook for about 8 minutes or until fully cooked through.\n"
        				 + "Add the red bell pepper and green beans and cook for 4 to 5 more minutes just until softened a bit.\n"
        				 + "Finish off with the basil, cilantro, and the cornstarch slurry. Mix together and the curry will start to thicken up a bit.\n"
        				 + "Take off the heat and enjoy it with rice!\n"
        				 + "Start by mixing sweet rice flour and salt in a large bowl. Gradually add hot water, stirring with a wooden spoon or spatula until the mixture comes together into a dough. The dough should be slightly sticky but firm enough to hold its shape.\n"
        				 + "Transfer the dough to a clean surface and knead it for about 5 minutes until smooth and elastic. If the dough is too sticky, dust your hands with a bit of rice flour as you knead.\n"
        				 + "Divide the dough into small portions and roll each one into a long, thin cylinder, about the thickness of your thumb. You can cut the cylinders into smaller, bite-sized pieces now.\n"
        				 + "To prevent sticking, lightly coat the rice cakes with sesame oil. This also helps to keep them tender during cooking.\n"
        				 + "Bring a large pot of water to a boil. Add the rice cakes and cook them for about 8 to 10 minutes, or until they float to the surface and become chewy.\n"
        				 + "Drain the rice cakes and rinse them under cold water to stop the cooking process. Set them aside while you prepare the sauce.\n"
        				 + "MAKING THE SAUCE\n"
        				 + "In a large pan or skillet, melt the unsalted butter over medium heat. Add the minced garlic and sauté until it becomes fragrant and lightly golden.\n"
        				 + "Pour in the hot water, gochujang paste, and gochugaru. Stir everything together until the gochujang is fully dissolved, and the sauce starts to simmer.\n"
        				 + "Add the white sugar to balance out the heat from the gochujang and gochugaru. Stir until the sugar dissolves completely.\n"
        				 + "Next, stir in the grated parmesan and heavy cream.\n"
        				 + "Taste the sauce and add a pinch of salt if needed. Let the sauce simmer for a few minutes until it thickens slightly.\n"
        				 + "Preheat your oven to 350°F (175°C).\n"
        				 + "Slice the top off each croissant and gently carve out the center, creating a boat-like shape. Be careful not to cut through the bottom or sides.\n"
        				 + "Press down the remaining center of the croissant to create a well for the fillings.\n"
        				 + "Method #1: Bacon and Cheddar\n"
        				 + "Sprinkle shredded cheddar cheese into the well of each of 4 croissants.\n"
        				 + "Place a strip of beef bacon on top of the cheese in the well.\n"
        				 + "Crack an egg into each croissant boat, directly on top of the bacon and cheese.\n"
        				 + "Season with salt and black pepper to taste.\n"
        				 + "Add a little bit more cheese on top.\n"
        				 + "Place the filled croissants on a baking sheet and bake in the preheated oven for 15-20 minutes, or until the eggs are set and the croissants are golden.\n"
        				 + "Method #2: Tomato, Basil, and Feta\n"
        				 + "In a bowl, whisk together the 6 eggs, salt, black pepper, and Italian seasoning.\n"
        				 + "Add the diced grape tomatoes, chopped basil, and crumbled feta cheese to the egg mixture. Mix together gently.\n"
        				 + "Spoon the mixture into the remaining 4 croissants, filling them evenly.\n"
        				 + "Place the filled croissants on a baking sheet and bake in the preheated oven for 15-20 minutes, or until the eggs are set and the croissants are golden.\n"
        				 + "Serve:\n"
        				 + "Remove the croissant egg boats from the oven and let them cool slightly before serving.\n"
        				 + "Enjoy these delicious croissant egg boats warm, perfect for a hearty breakfast or brunch!\n"
        				 + "Start by combining brown sugar and water in a saucepan over medium heat.\n"
        				 + "Bring the mixture to a gentle boil, stirring continuously to ensure the sugar dissolves completely and the mixture is smooth.\n"
        				 + "Once the sugar is fully dissolved, reduce the heat and add the vanilla bean paste. Stir well to incorporate the vanilla throughout the syrup.\n"
        				 + "Let it simmer for 5 to 10 minutes to thicken slightly.\n"
        				 + "Remove the saucepan from the heat and allow the syrup to cool before pouring it into a bottle or jar.\n"
        				 + "Store at room temp on the counter for 1 to 2 weeks and in the fridge for any longer.\n"
        				 + "MAPLE PUMPKIN SAUCE\n"
        				 + "In a saucepan over medium heat, combine water, pumpkin puree, maple syrup, and brown sugar. Stir until the sugar has dissolved and everything is well blended.\n"
        				 + "Stir in pumpkin spice and cinnamon, making sure they are evenly distributed throughout the mixture.\n"
        				 + "Allow the mixture to simmer gently, stirring occasionally, until it thickens to your desired consistency. This will let the flavors meld together beautifully.\n"
        				 + "MAKE THE CHOCOLATE COOKIE DOUGH:\n"
        				 + "Cream together butter and both granulated and brown sugars until smooth and creamy.\n"
        				 + "Add an egg, an extra yolk, and vanilla extract, mixing until fully incorporated.\n"
        				 + "In a separate bowl, whisk together cocoa powder, flour, cornstarch, baking soda, and salt.\n"
        				 + "Gradually combine the dry ingredients with the wet mixture until a dough forms.\n"
        				 + "Fold in semi-sweet and milk chocolate chips, then set the dough aside.\n"
        				 + "MAKE THE GRAHAM CRACKER COOKIE DOUGH:\n"
        				 + "In a mixing bowl, add graham cracker crumbs, flour, salt, butter, brown sugar, and vanilla extract.\n"
        				 + "Beat together with a hand or stand mixer until light and fluffy. Set the dough aside.\n"
        				 + "PREPARE THE BROWNIE LAYER:\n"
        				 + "Melt the unsalted butter in the microwave.\n"
        				 + "Add chocolate chips to the hot butter, let it sit for 5 to 10 minutes, and then mix together until completely smooth.\n"
        				 + "Whisk in cocoa powder until completely smooth again.\n"
        				 + "In another bowl, beat together an egg and both granulated and brown sugar until completely smooth and lighter in color.\n"
        				 + "Fold in the chocolate and creamed butter mixtures together and add the flour and salt.\n"
        				 + "Combine with a rubber spatula until you have a thick brownie batter consistency.\n"
        				 + "Cover and transfer in the fridge to chill for 1o to 15 minutes to thicken up a bit.\n"
        				 + "ASSEMBLE AND BAKE THE COOKIES:\n"
        				 + "Preheat your oven to 350°F (175°C) and line a baking sheet with parchment paper.\n"
        				 + "Use a large cookie scoop to portion the chocolate cookie dough into 10 to 11 pieces. Flatten each piece into a thinner disc.\n"
        				 + "Add about 1 to 2 tablespoons of the graham cracker cookie dough on top and flatten it.\n"
        				 + "Place 1 to 2 tablespoons of the brownie base on top of the graham cracker dough and press down to flatten slightly.\n"
        				 + "Top each cookie with two marshmallow halves.\n"
        				 + "Sprinkle graham cracker crumbs on top and the edges of the cookies.\n"
        				 + "Bake until the edges are set, but the centers remain slightly soft, about 10 to 12 minutes.\n"
        				 + "Remove from the oven and allow to rest for 10 minutes on the tray. Then enjoy warm!\n"
        				 + "cook for (1 (minute)\n"
        				 + "cook for twenty-five minutes\n";
        
        try {
            RecipeLineProcessor rlp = new RecipeLineProcessor("food_ingredient_database_cleaned.txt");
            rlp.processFullRecipe(paragraph);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
