name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_java:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK 11 (or any other version you need)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Compile the Java program
    - name: Compile Java program
      run: javac -d out src/cs5279_recipe_parser/Main.java src/cs5279_recipe_parser/RecipeLineProcessor.java

    # Run the Java program and capture the output
    - name: Run Java program
      run: java -cp out cs5279_recipe_parser.Main > program_output.txt
    
    # Always save the program output as an artifact, even if the diff fails
    - name: Upload program output
      uses: actions/upload-artifact@v3
      with:
        name: program-output
        path: program_output.txt
    # Compare the output with the expected output file
    - name: Compare output
      run: diff -q program_output.txt src/cs5279_recipe_parser/expected_output.txt


  build_python:
    # If the output matches, the test passes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # Run the Python program and save its output to `python_output.txt`
    - name: Run Python program
      run: python src_python/url_recipe_fetcher.py > python_output.txt

    # Always save the Python program output as an artifact
    - name: Upload Python program output
      uses: actions/upload-artifact@v3
      with:
        name: python-program-output
        path: python_output.txt
    # Compare the Python program output with an expected output file
    - name: Compare Python output
      run: diff -q python_output.txt src_python/expected_python_output.txt